<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>684a6571-32b2-49c3-a345-66f0b5437e3b</elementGuidId>
    <imagePath></imagePath>
    <name>button_checkout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#checkout</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'checkout') and equals(@name,'checkout') and equals(@class,'btn btn_action btn_medium checkout_button ')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_action btn_medium checkout_button </value>
        <webElementGuid>bdae4e73-6780-4656-b365-b72a06915562</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>checkout</value>
        <webElementGuid>fc761aec-4117-45c7-92cc-a3bf003b653b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>checkout</value>
        <webElementGuid>5f8b94fb-e912-40e1-867e-a95239053e1d</webElementGuid>
    </webElementProperties>
</WebElementEntity>