<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>82f6429a-c352-44da-8c2e-309cef688f45</elementGuidId>
    <imagePath></imagePath>
    <name>input_firstname</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#first-name</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'first-name') and equals(@name,'firstName') and equals(@class,'input_error form_input')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input_error form_input</value>
        <webElementGuid>c4860c94-aea8-4190-80f4-bb848a7a2ce1</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>first-name</value>
        <webElementGuid>70b93a58-3974-4c4b-8ad2-6d8600261e25</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>firstName</value>
        <webElementGuid>01d8cd88-901b-4a20-8b53-26ffc072b85c</webElementGuid>
    </webElementProperties>
</WebElementEntity>